# ==========================================================================================
# Author: Pablo González García.
# Created: 13/01/2026
# Last edited: 13/01/2026
# ==========================================================================================


# Grafana users.
users:
  - name: admin
    # Admin password (plaintext here, Grafana hashes internally)
    password: admin
    # Admin email (required in Grafana 10+).
    email: admin@nyx.com
    # Role for the user.
    orgRole: Admin
    # Whether the user is the Grafana login admin.
    isAdmin: true
    # Login enabled.
    login: true