# ==========================================================================================
# Author: Pablo González García.
# Created: 17/12/2025
# Last edited: 23/12/2025
# ==========================================================================================


# ==============================
# CONFIGURATION
# ==============================

# Log level configuration.
log_level: INFO

# Service configuration.
service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334

# Storage configuration.
storage:
  storage_path: /qdrant/storage

telemetry_disabled: false