# ==========================================================================================
# Author: Pablo González García.
# Created: 16/02/2026
# Last edited: 16/02/2026
# ==========================================================================================


# ==============================
# gRPC
# ==============================

grpc:

  max_concurrent_rpcs: 64
  max_receive_message_length: 67108864            # 64 MB.
  max_send_message_length: 67108864               # 64 MB.
  keep_alive_time_ms: 30000                       # 30 seconds.
  keepalive_timeout_ms: 10000                     # 10 seconds.
  keepalive_permit_without_calls: 1
  max_pings_without_data: 0
  min_recv_ping_interval_without_data_ms: 10000   # 10 seconds.