# ==========================================================================================
# Author: Pablo González García.
# Created: 23/01/2026
# Last edited: 23/01/2026
# ==========================================================================================


# ==============================
# TASKS
# ==============================

tasks:

  embedding:
    model: bge_m3_ensemble

  text-generation:
    model: null

  classification:
    model: null