# ==========================================================================================
# Author: Pablo González García.
# Created: 20/01/2025
# Last edited: 20/01/2025
#
# Defines the mapping between AI tasks and their corresponding model deployments.
#
# This file serves as the central registry for ALL model deployments.
# Each task type can only have one model.
# ==========================================================================================


# ==============================
# MAPPING
# ==============================

tasks:

  # Convert text into dense vector representations for similarity
  # search.
  embedding:
    model: multilingual_e5_base           # Name of the model.
    server: triton-onnx                   # Backend server cluster/container.

  # Categorize text into predefined classes or labels.
  classification:
    model: None                           # Name of the model.
    server: triton-onnx                   # Backend server cluster/container.

  # Generate human-like text from prompts.
  text_generation:
    model: None                           # Name of the model.
    server: triton-vllm                   # Backend server cluster/container.