# ==========================================================================================
# Author: Pablo González García.
# Created: 23/01/2026
# Last edited: 23/01/2026
# ==========================================================================================


# ==============================
# SERVERS
# ==============================

servers:

  triton-onnx:
    host: triton-onnx
    http_port: 8000
    grpc_port: 8001
  
  triton-vllm:
    host: triton-vllm
    http_port: 8000
    grpc_port: 8001