# ==========================================================================================
# Author: Pablo González García.
# Created: 15/12/2025
# Last edited: 15/12/2025
# ==========================================================================================


# ==============================
# SERVICES
# ==============================

# All Services available.
services:
  # Intent Classifier Service.
  ic:
    host: "localhost"
    port: 10000