# ==========================================================================================
# Author: Pablo González García.
# Created: 18/12/2025
# Last edited: 18/12/2025
# ==========================================================================================


# ==============================
# CORE
# ==============================

# Host and port.
host: '0.0.0.0'
port: 8000
# Websocket ping interval and timeout.
ws_ping_interval: 15
ws_ping_timeout: 30