# ==========================================================================================
# Author: Pablo González García.
# Created: 13/02/2026
# Last edited: 13/02/2026
# ==========================================================================================

# ==============================
# CONFIGURATION
# ==============================

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true